trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - docs/
    - /**/docs/*
    - /**/*.md

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - docs/
    - /**/docs/*
    - /**/*.md

jobs:
- job: Lin

  # About 150% of total time
  timeoutInMinutes: 120

  pool:
    name: LIN_VMSS_VENV_F16S_U20_WU2

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    WORK_DIR: $(Pipeline.Workspace)/_w

  steps:
  - bash: |
      echo "someToken: $(someToken)"
      echo "github_token: $(github_token)"
  
